input_dir: ../resources
output_dir: ../resources/.gen

strings:
  inputs:
    - en.lproj/Localizable.strings
    - en.lproj/Localizable.stringsdict
  outputs:
    - templateName: structured-swift5
      output: Strings.generated.swift

xcassets:
  inputs: [assets/Assets.xcassets]
  outputs:
    templateName: swift5
    output: Assets.generated.swift
